### PR TITLE
Update MLX90621IRArray.ino

### PR DESCRIPTION
**Pull request by riodda**
Hopefoully adds the correction factors for BAA 120° fov sensor.

### CODE REVIEW

**Comment by kriswiner** [comment]
Where did these modified formulas come from?

Why would you use int? Is this supposed to be int16_t?

Does this fix your problem?

**Comment by riodda** [comment]
The formulas are coming from the MLX90621 datasheet  Rev 3.0 page 19 "Calculating Ks4"
I think the int is wrong, sorry.
Haven't tested yet hopefoully with serveral fingers crossed.

**Comment by kriswiner** [comment]
The calculation of ks4 is not correct.

Should be:

ks_scale = (uint8_t) eepromData[KS_SCALE];

ks4 = (float) (((int16_t)eepromData[KS4_EE] << 8) >> 8) / pow(2,ks_scale+8);

Otherwise this is fine.

**Review by kriswiner — APPROVED** [review]

**Review by kriswiner — APPROVED** [review]

**Comment by kriswiner** [comment]
OK, I accepted the pull request and changed the above, so it should be
correct. Give it a try and see...

**Comment by riodda** [comment]
Thanks Kris, i will give it a try, about the KS_SCALE on the datasheet PAGE 28 it states KS_SCALE is bit 3 to 0 shouldn't  get rid of the other 4 bits ?

**Comment by kriswiner** [comment]
Yes, made the change.

**Comment by kriswiner** [comment]
I just tried it on my hand and it seems to work well.

**Comment by riodda** [comment]
Hi Kris, i think there is also another issue with the 8bit registers i've realized it when i tryed to check the Ks4 calculation.
With your original code 
`ks4 = (float) (((int16_t)eepromData[KS4_EE] << 8) >> 8) / pow(2, ks_scale + 8);` 
on my sensor i have KS4_EE = 158 but the Ks4 calculation outputs 
ks4 = 0.00120544 while according to the datasheet with 158 i should have 
ks4 = -7.4768 E-4
I've noticed this on all the 8 bit registers, i made a change to my code as 
`  ks4 = ((int16_t)eepromData[KS4_EE] << 8) >> 8;
     if (ks4 > 127 )  ks4 -= 256;
   ks4  = (float) ks4 / pow(2, ks_scale + 8);`

But io haven't pushed it since i'm not sure is the best way to do it, i guess that storing the register into an int8_t and then moving to a int16_t should propagate the right sign.

**Comment by kriswiner** [comment]
Maybe this need to be:

ks4 = (float) ( (int16_t)(eepromData[KS4_EE] << 8) >> 8 ) / pow(2, ks_scale
+ 8);

**Pull request merged**
